---
- name: restart libvirt
  ansible.builtin.systemd:
    name: "{{ libvirt_primary_service }}"
    state: restarted

- name: reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
