version: "3"
virtualmachines:
- name: kvm-host
  image: suse/harv-rodeo-183-test
  memory: 92160
  cpus: 38
  allow_external_ingress:
  - https
  - high-ports
  - http
  nested_virtualization: true
  provision_ssl_certificate: true
