#!/bin/bash

source ~/.bashrc


# Configure a new context to access Harvester cluster through Rancher
kubectl config set-credentials rancher-bearer --token=$RANCHER_TOKEN
kubectl config set-cluster susevirt-through-rancher --server=https://$HARVESTER_NAT_IP:30002/k8s/clusters/$(k --context rancher get clusters.provisioning.cattle.io harvester -n fleet-default -o yaml | yq -r .status.clusterName) --insecure-skip-tls-verify=true
kubectl config set-context susevirt-through-rancher --cluster susevirt-through-rancher --user rancher-bearer
kubectl config use-context susevirt-through-rancher

cat <<EOF | kubectl apply  -f -
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-csi-vm
parameters:
  io_profile: auto
  repl: "2"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
EOF

kubectl patch storageclass harvester-longhorn -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
kubectl patch storageclass px-csi-vm -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

# I am so sorry...
LEAP_IMAGE=$(\
curl -s https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.6/images/ | \
grep -oP 'openSUSE-Leap-15.6\.x86_64-1\.0\.2-NoCloud[^"]+\.qcow2' | \
head -n 1 | \
xargs -I {} echo "https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.6/images/{}"\
)

agent variable set LEAP_IMAGE $LEAP_IMAGE