#!/bin/bash
set -euxo pipefail

if grep -q "osv-autopilot-mongo-cleaned" "/root/cleanup_status.txt"; then
        echo "Cleanup script for challenge 3 complete"
else
        fail-message "Did you forget to run the cleanup.sh script?"
        exit 1
fi

rm -rf /root/cleanup.sh

exit 0
