#!/bin/bash

source ~/.bashrc

# Ensure the VM is running
virtctl start vm2

until ssh vm2 date; do sleep 10;done


# enabled autopilot:
kubectl -n portworx patch stc px-cluster --type merge -p '{"spec":{"autopilot":{"enabled":true}}}'

cat << EOF > autopilotrule.yaml
apiVersion: autopilot.libopenstorage.org/v1alpha1
kind: AutopilotRule
metadata:
 name: volume-resize
spec:
  ##### selector filters the objects affected by this rule given labels
  selector:
    matchLabels:
      auto_expand: "on"
  ##### namespaceSelector selects the namespaces of the objects affected by this rule
  namespaceSelector:
    matchLabels:
      auto_expand: "on"
  ##### conditions are the symptoms to evaluate. All conditions are AND'ed
  conditions:
    # volume usage should be less than 10%
    expressions:
    - key: "100 * (px_volume_usage_bytes / px_volume_capacity_bytes)"
      operator: Gt
      values:
        - "10"
    for: 5
  ##### action to perform when condition is true
  actions:
  - name: openstorage.io.action.volume/resize
    params:
      # resize volume by scalepercentage of current size
      scalepercentage: "100"
      # volume capacity should not exceed 75GiB
      maxsize: "75Gi"
EOF

cat << EOF > ~/cleanup.sh
#!/bin/bash

source /root/.profile

echo "osv-autopilot-mongo-cleaned" >> cleanup_status.txt
echo "--------------------------------"
clear
echo "Cleanup complete - let's move to the next scenario by clicking the Check button!"

EOF

chmod +x ~/cleanup.sh