#!/bin/bash

source ~/.bashrc

# Configure an SSH config item to make accessing vm1 easier
cat << EOF >> ~/.ssh/config
Host vm1
  Hostname $HARVESTER_NAT_IP
  User ubuntu
  IdentityFile ~/.ssh/id_rsa
  StrictHostKeyChecking no
  port 2223
EOF

# Create a KeyPair object
kubectl config use-context susevirt-through-rancher
cat << EOF | kubectl apply -f -
apiVersion: harvesterhci.io/v1beta1
kind: KeyPair
metadata:
  name: cloud-client
  namespace: default
spec:
  publicKey: >-
    $(cat .ssh/id_rsa.pub)
EOF

# Create a ubuntu cloud-init template.

kubectl config use-context susevirt-through-rancher
cat << EOF | kubectl create -f -
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  annotations:
    harvesterhci.io/storageClassName: px-csi-vm
  generateName: image-
  generation: 17
  labels:
    harvesterhci.io/image-type: raw_qcow2
    harvesterhci.io/imageDisplayName: ubuntu
    harvesterhci.io/os-type: ubuntu
  namespace: default
spec:
  backend: cdi
  checksum: ""
  displayName: ubuntu
  pvcName: ""
  pvcNamespace: ""
  retry: 3
  sourceType: download
  targetStorageClassName: px-csi-vm
  url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
EOF