#!/usr/bin/env bash


source ~/.bashrc


#################################################################
# Version
# 0.3.4-dev - Mung

### 0.2.16
# - [x] First tracked version

### 0.3.1

### 0.3.2

### 0.3.3

### 0.3.4
# - Add Cleanup of FASIM Access for sandbox principal
# - updtae envs for 0.3.4

### 0.3.5
# -


#################################################################
### Global Variables
###########
# Error Codes
readonly ERR_DEFAULT=1
readonly ERR_TRY_FAILED=160
readonly ERR_NO_GCP_REGIONS_LEFT=161
readonly ERR_OCP_FEATURE_FLAG=162
readonly ERR_AWS_FEATURE_FLAG=163
readonly ERR_CURL_FAILED=164
readonly ERR_VALIDATE_FAILED=165
readonly ERR_WAIT_READY_TIMEOUT=166

###########
# Global Variables

SSH_ID_NAME="/root/.ssh/id_rsa_instruqt"
SSH_ID_NAME_PUB="${SSH_ID_NAME}.pub"
OCP_INSTALL_DIR="/root/ocp-install"
OCP_VERSION="4.19.1"
PXBACKUP_VERSION="2.8.1"
PXBACKUP_SC="px-csi-db"
GKE_CLUSTERNAME="portworx-cluster"
GKE_CLUSTERNAME_DR="portworx-cluster-dr"
PX_CLUSTERNAME="px-cluster"
PX_VERSION="3.3.1.1"
PX_VERSION_UPGRADEFROM="3.3.0"
AWS_DNS_ZONE_ID="Z061552929RQK6D7Z1IUD"
RANCHER_DNS_NAME="rancher-${INSTRUQT_PARTICIPANT_ID}.pxlab.io"
PXBACKUP_DNS_NAME="pxbackup-${INSTRUQT_PARTICIPANT_ID}.pxlab.io"
FASIM_UI_DNS_NAME="fa-${INSTRUQT_PARTICIPANT_ID}.tme-internal.pxlab.io"
PX_CSI_PXBBQ_DNS_NAME="pxbbq-${INSTRUQT_PARTICIPANT_ID}.tme-internal.pxlab.io"
FASIM_IMAGE_NAME="fasim1-2025082025"
# This is a tricky variable. If the GCP feature flag is enabled, it will be updated with the stable release of GKE within the region, based 
# on the major.minor version of GKE_VERSION
# If it is not enabled, it can be overridden by rancher, but not before this version of kubectl is installed. This is important because it does
# not directly control the rancher version, which is set by the RANCHER_K8S_Version variable. Honestly this variable should not have a value initially, but we need something
# set to know what version of kubectl to download in the absence of the GCP flag
K8SVERSION="1.32.6"

GKE_VERSION="1.32"
BASHRC_FILE="/root/.bashrc"
MINIO_VERSION="5.2.0"
MINIO_SC="px-csi-db"
UTILVM_NAME="util1"
RANCHER_VERSION="v2.10.3"
RANCHER_PASSWORD="gr9o3rNpvgrc6lpA"
RANCHER_SERVER_CONTEXT="rancher"
RANCHER_K8S_VERSION="v1.31.5+rke2r1"
RANCHER_CLUSTER_NAME="cluster1"
RANCHER_DNS_NAME="rancher-${INSTRUQT_PARTICIPANT_ID}.pxlab.io"
UBUNTU_IMAGE_NAME="ubuntu-2204-jammy-v" # this image name is updated by get_ubuntu_image function
RANCHER_UI_PLUGIN_VERSION="1.0.0-rc9"
PX_OPERATOR_CSV="portworx-operator.v24.2.3"
CERT_MGR_VERSION="v1.17.0"
KIND_VERSION="v0.27.0"
OSV_OPERATOR_VERSION="v4.19.1"
VIRTCTL_VERSION="v1.5.0"
HELM_VERSION="v3.18.1"

PXBACKUP_DNS_NAME="pxbackup-${INSTRUQT_PARTICIPANT_ID}.pxlab.io"
OCP_DNS_ZONE="${INSTRUQT_PARTICIPANT_ID}.pxlab.io"
OCP_CONSOLE_URL="https://console-openshift-console.apps.ocp.${OCP_DNS_ZONE}"
OCP_OAUTH_URL="https://oauth-openshift.apps.ocp.${OCP_DNS_ZONE}"
OCP_API_URI="https://api.ocp.${OCP_DNS_ZONE}:6443"

# This is the amount of loop interations before we break. 10 sec per loop
WAIT_READY_TIMEOUT=50


# These two variables will configure the values used for the validate_* function (unless they are hard coded)
# They are passed to try functions that are used.
VALIDATE_RETRY=5
VALIDATE_WAIT=6
SSH_ID_PUB=""
OCP_INSTALL_DIR="/root/ocp-install"
# This script is hacky at best


#################################################################
# Standard Functions

log () {
  if [[ ${feature_LOG_TIMESTAMP} == true ]]; then
    echo $(date -u +"%Y-%m-%dT%H:%M:%SZ") "${@}"
  else 
    echo "${@}"
  fi
}

debug () {
  if [[ ${DEBUG} == 1 ]]; then
    log "DEBUG: ${@}"
  fi
}

terminate () {
  local msg="${1}"
  local code="${2:-1}"
  collect_debug
  echo "Error: ${msg}" >&2

  if [[ $feature_TERMINATE_BYPASS == true ]]; then
    log "Bypassing terminate function"
    echo "I would have exited with code: ${code}"
    return 0
  fi
  
  exit "${code}"
}


#################################################################
### Script Start

# Remove the Portworx license
kubectl config use-context cluster1
alias pxctl="PX_POD=$(kubectl get pods -l name=portworx -n portworx -o jsonpath='{.items[0].metadata.name}') && kubectl exec \$PX_POD -n portworx -- /opt/pwx/bin/pxctl"
declare -i i=0
until [[ $i -ge 3 ]]
do
    pxctl license activate --ep UAT -n 0 ${PXENT_LICENSE}
    if [[ $? -eq 0 ]]; then
        break
    fi
    sleep 10
    i=$i+1
done

kubectl config use-context cluster2
alias pxctl="PX_POD=$(kubectl get pods -l name=portworx -n portworx -o jsonpath='{.items[0].metadata.name}') && kubectl exec \$PX_POD -n portworx -- /opt/pwx/bin/pxctl"
declare -i i=0
until [[ $i -ge 3 ]]
do
    pxctl license activate --ep UAT -n 0 ${PXENT_LICENSE}
    if [[ $? -eq 0 ]]; then
        break
    fi
    sleep 10
    i=$i+1
done

# Remove AWS NS record
aws configure set aws_access_key_id ${PURE_ROUTE53_ACCESSKEY}
aws configure set aws_secret_access_key ${PURE_ROUTE53_SECRETKEY}
aws configure set default.region "us-west-2"
aws configure set default.output "json"
sleep 10
# The file should already exist, let's change it to a delete record:
jq '.Changes[].Action = "DELETE"' change-resource-record-sets.json > updated-change-resource-record-sets.json
jq '.Changes[].Action = "DELETE"' change-resource-record-sets-rancher.json > updated-change-resource-record-sets-rancher.json
jq '.Changes[].Action = "DELETE"' change-resource-record-sets-pxbackup.json > updated-change-resource-record-sets-pxbackup.json
jq '.Changes[].Action = "DELETE"' change-resource-record-sets-pxbackup.json > updated-change-resource-record-sets-harvester.json
jq '.Changes |= map(.Action = "DELETE")' change-resource-record-sets-pxcsi.json > updated-change-resource-record-sets-pxcsi.json

cat updated-change-resource-record-sets.json
cat updated-change-resource-record-sets-rancher.json
cat updated-change-resource-record-sets-pxbackup.json
cat updated-change-resource-record-sets-pxcsi.json
cat updated-change-resource-record-sets-harvester.json
aws route53 change-resource-record-sets --hosted-zone-id $AWS_DNS_ZONE_ID --change-batch file://updated-change-resource-record-sets.json
aws route53 change-resource-record-sets --hosted-zone-id $AWS_DNS_ZONE_ID --change-batch file://updated-change-resource-record-sets-rancher.json
aws route53 change-resource-record-sets --hosted-zone-id $AWS_DNS_ZONE_ID --change-batch file://updated-change-resource-record-sets-pxbackup.json
aws route53 change-resource-record-sets --hosted-zone-id $AWS_DNS_ZONE_ID --change-batch file://updated-change-resource-record-sets-pxcsi.json
aws route53 change-resource-record-sets --hosted-zone-id $AWS_DNS_ZONE_ID --change-batch file://updated-change-resource-record-sets-harvester.json

sleep 10

gcloud compute firewall-rules delete allow-all-ports --quiet

/root/openshift-install --dir=${OCP_INSTALL_DIR} destroy cluster

# Try and cleanup access to fasim
gcloud config configurations create instruqt-sa
gcloud config configurations activate instruqt-sa
echo "$PURE_ANTHOS_SA_KEY" > /tmp/pure-anthos-instruqt-sa-key.json
gcloud auth activate-service-account \
 --key-file=/tmp/pure-anthos-instruqt-sa-key.json \
 --project=pure-anthos
gcloud compute images remove-iam-policy-binding $FASIM_IMAGE_NAME \
  --project=pure-anthos \
  --member=serviceAccount:$INSTRUQT_GCP_PROJECT_GCPPROJECT_SERVICE_ACCOUNT_EMAIL \
  --role=roles/compute.imageUser
